apiVersion: kubevirt.io/v1
kind: VirtualMachineInstance
metadata:
  name: vmi-test-basic
spec:
  domain:
    devices:
      disks:
      - name: containerdisk
        disk:
          bus: virtio
    resources:
      requests:
        memory: 256M
  volumes:
  - name: containerdisk
    containerDisk:
      image: quay.io/kubevirt/cirros-container-disk-demo