apiVersion: kubevirt.io/v1
kind: VirtualMachineInstance
metadata:
  name: vmi-vnc-test
spec:
  domain:
    devices:
      disks:
      - disk:
          bus: virtio
        name: containerdisk
      interfaces:
      - name: default
        masquerade: {}
    resources:
      requests:
        memory: 256M
  networks:
  - name: default
    pod: {}
  volumes:
  - containerDisk:
      image: quay.io/kubevirt/cirros-container-disk-demo
    name: containerdisk
  directVNCAccess:
    port: 5901