apiVersion: v1
kind: ServiceAccount
metadata:
  name: vnc-proxy-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: vnc-proxy-role
rules:
- apiGroups: [""]
  resources: ["pods", "pods/portforward"]
  verbs: ["get", "list", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vnc-proxy-rolebinding
subjects:
- kind: ServiceAccount
  name: vnc-proxy-sa
roleRef:
  kind: Role
  name: vnc-proxy-role
  apiGroup: rbac.authorization.k8s.io
